import type { Metadata } from "next";
import Theme from "./ui/theme";
import { Inter } from "next/font/google";
import Navbar from "./ui/navbar";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  h-screen overflow-x-hidden `}>
        <div className="flex justify-between md:max-h-28 lg:max-h-28">
          <Navbar />
          <Theme />
        </div>
        {children}
      </body>
    </html>
  );
}
